version: "2"

services:
  runtime:
    image: public.ecr.aws/nupano/nupano-runtime:latest
    environment:
      - LOGGING_LEVEL_COM_NUPANO=DEBUG
      - NUPANO_DESCRIPTION_MANUFACTURER=Brillinger
      - NUPANO_DESCRIPTION_MODEL_NAME=B1000BALENA
    volumes:
      - nupano_data:/nupano
    networks:
      - nupano_network
    ports:
      - 61100:61100/tcp
      - 61101:61101/tcp
      - 61106:61106/tcp
    labels:      
      io.resin.features.balena-socket: '1'

  discovery:
    image: public.ecr.aws/nupano/nupano-runtime-discovery:latest
    network_mode: host    

  updater:
    image: public.ecr.aws/nupano/nupano-runtime-updater:latest    
    volumes:
      - nupano_data:/nupano
    networks:
      - nupano_network
    ports:
      - 61107:61107/tcp
    labels:      
      io.resin.features.balena-socket: '1'

networks:
  nupano_network:
    driver: bridge

volumes:
  nupano_data: